"""Bibliothèque de clauses — extension (familles classiques des contrats d'affaires).

Textes rédigés pour Massey (aucune reproduction d'un ouvrage). Les crochets [ ] sont à adapter.
Chaque clause est une proposition de départ : elle ne remplace pas la relecture par un avocat,
et l'adaptation au droit haïtien (Code civil, droit commercial, fiscalité) reste à valider.
"""
NEW_CATEGORIES = [
    ("duree", "Durée et reconduction", "Term and renewal"),
    ("prix", "Prix, révision et devises", "Price, revision and currency"),
    ("responsabilite", "Responsabilité et garanties", "Liability and warranties"),
    ("exclusivite", "Exclusivité et non-sollicitation", "Exclusivity and non-solicitation"),
    ("propriete", "Réserve de propriété, livraison et risques", "Retention of title, delivery and risk"),
    ("propriete_intellectuelle", "Propriété intellectuelle", "Intellectual property"),
    ("cession", "Cession, sous-traitance et contrôle", "Assignment, subcontracting and control"),
    ("donnees", "Protection des données", "Data protection"),
    ("imprevision", "Imprévision et renégociation", "Hardship and renegotiation"),
    ("droit_applicable", "Droit applicable, langue et juridiction", "Governing law, language and jurisdiction"),
    ("clauses_finales", "Clauses finales", "Final clauses"),
    ("assurance_audit", "Assurance, audit et information", "Insurance, audit and information"),
]

# (titre, catégorie, risque, texte, conseil)
CLAUSES = [
    # --- Définitions et principes
    ("Définitions", "general", "standard",
     "Les termes commençant par une majuscule ont le sens qui leur est donné ci-après ou à l'endroit du contrat où ils sont définis : « Contrat » désigne le présent contrat et ses annexes ; « Livrables » désigne [description] ; « Informations confidentielles » désigne [définition] ; « Jour ouvrable » désigne tout jour autre qu'un samedi, un dimanche ou un jour férié en Haïti.",
     "Ne définir que les termes réellement utilisés et employer chacun de façon identique dans tout le contrat : un terme défini mais utilisé de deux manières crée de l'ambiguïté."),
    ("Bonne foi et coopération", "general", "standard",
     "Les parties exécutent le Contrat de bonne foi et coopèrent loyalement. Chacune informe sans délai l'autre de toute difficulté de nature à compromettre l'exécution du Contrat dans les délais ou conditions convenus.",
     "Clause d'esprit plus que de sanction : utile pour fonder une obligation d'information et d'alerte en cas de litige."),
    ("Indépendance des parties", "general", "standard",
     "Chaque partie agit en son nom et pour son compte. Le Contrat ne crée entre elles ni société, ni mandat, ni relation d'emploi, ni lien d'agence, et aucune ne peut engager l'autre sans son accord écrit préalable.",
     "Essentielle pour les prestataires indépendants et les distributeurs : réduit le risque de requalification en contrat de travail ou en mandat."),
    ("Contrat conclu en considération de la personne (intuitu personae)", "general", "a_negocier",
     "Le Contrat est conclu en considération de la personne du Prestataire et de [son équipe / ses dirigeants]. Il ne peut être cédé ni exécuté par un tiers sans l'accord écrit préalable du Client.",
     "À réserver aux prestations où l'identité ou la compétence du cocontractant est déterminante ; à coordonner avec la clause de sous-traitance."),

    # --- Durée
    ("Durée déterminée et date d'effet", "duree", "standard",
     "Le Contrat prend effet le [date] pour une durée de [durée]. Il prend fin de plein droit à son terme, sans qu'il soit besoin d'une formalité, sauf prolongation convenue par avenant écrit signé des deux parties.",
     "Indiquer une date d'effet précise : c'est le point de départ de tous les délais (paiement, préavis, garanties)."),
    ("Reconduction tacite encadrée", "duree", "a_negocier",
     "À l'expiration de la durée initiale, le Contrat est reconduit pour des périodes successives de [durée] sauf dénonciation notifiée par écrit au moins [60] jours avant l'échéance. Le Prestataire rappelle cette faculté de dénonciation au Client par écrit entre [90] et [60] jours avant l'échéance.",
     "La reconduction tacite piège souvent la partie qui oublie la date : prévoir un rappel écrit et inscrire la date limite de dénonciation dans l'outil d'échéances."),
    ("Réexamen périodique", "duree", "standard",
     "Les parties se réunissent au moins une fois par [semestre] pour examiner l'exécution du Contrat, les performances atteintes et, le cas échéant, les ajustements à convenir par avenant.",
     "Utile pour les contrats de longue durée ; évite de recourir à la résiliation quand un simple ajustement suffit."),

    # --- Prix
    ("Prix ferme et non révisable", "prix", "standard",
     "Le prix est ferme et non révisable pendant la durée du Contrat. Il comprend tous les frais, sauf ceux expressément énumérés comme refacturables à l'article [ ].",
     "Bon pour le client ; le prestataire demandera une indexation si le contrat dépasse un an."),
    ("Indexation du prix", "prix", "a_negocier",
     "Le prix est révisé chaque année à la date anniversaire selon la formule P1 = P0 × (I1 / I0), où P0 est le prix initial, I0 l'indice [désigner l'indice] à la date de signature et I1 le dernier indice publié à la date de révision. Si l'indice cesse d'être publié, les parties conviennent d'un indice de remplacement équivalent.",
     "Choisir un indice vérifiable et publié régulièrement ; en l'absence d'indice local fiable, un indice international ou le taux de change peut servir de référence. Prévoir un plafond de variation si besoin."),
    ("Prix en devise étrangère et risque de change", "prix", "sensible",
     "Le prix est exprimé en [dollars américains (USD)] et payable en [gourdes (HTG)] au taux de référence [désigner la source] du jour précédant le paiement. [Le risque de variation du taux de change est supporté par [la partie]. / Si le taux varie de plus de [5] % entre la facturation et le paiement, les parties se concertent pour partager l'écart.]",
     "Dans un contexte de forte volatilité de la gourde, désigner la source du taux et la date de conversion ; vérifier les règles de change et de déclaration applicables."),
    ("Acompte et paiement échelonné", "paiement", "standard",
     "Le prix est payable comme suit : [30] % à la signature à titre d'acompte, [40] % à la livraison du premier Livrable et le solde de [30] % à la réception définitive. Aucun travail ne démarre avant réception de l'acompte.",
     "Lier chaque échéance à un événement objectif (livraison, réception) plutôt qu'à une date seule."),
    ("Intérêts de retard et frais de recouvrement", "paiement", "a_negocier",
     "Toute somme non payée à l'échéance porte intérêt de plein droit, sans mise en demeure, au taux de [taux] % par [mois / an] à compter du jour suivant l'échéance jusqu'au paiement complet, ainsi qu'une indemnité forfaitaire de [montant] pour frais de recouvrement, sans préjudice de tous dommages-intérêts complémentaires.",
     "Vérifier le plafond légal du taux d'intérêt conventionnel et la possibilité de capitaliser les intérêts ; un taux excessif peut être réduit."),
    ("Compensation conventionnelle", "paiement", "a_negocier",
     "Chaque partie peut compenser toute somme certaine, liquide et exigible qu'elle doit à l'autre au titre du Contrat avec toute somme de même nature que l'autre lui doit, après notification écrite précisant les montants compensés.",
     "À l'inverse, un fournisseur peut stipuler l'interdiction de toute compensation : décider dans quel sens négocier."),
    ("Déchéance du terme", "paiement", "sensible",
     "En cas de défaut de paiement d'une seule échéance resté sans effet [8] jours après mise en demeure, toutes les sommes restant dues deviennent immédiatement exigibles.",
     "Clause lourde : l'encadrer d'une mise en demeure préalable et la réserver aux paiements échelonnés."),

    # --- Responsabilité et garanties
    ("Limitation de responsabilité (plafond)", "responsabilite", "a_negocier",
     "La responsabilité totale de [partie] au titre du Contrat, toutes causes confondues, est limitée à [le montant du prix payé ou payable au cours des douze mois précédant le fait générateur / un montant de [montant]]. Cette limite ne s'applique pas en cas de faute lourde ou dolosive, de dommage corporel ni à l'obligation de confidentialité.",
     "Une limitation est écartée en cas de faute lourde ou de dol : le prévoir expressément renforce la validité de la clause. Le plafond doit rester cohérent avec la couverture d'assurance."),
    ("Exclusion des dommages indirects", "responsabilite", "a_negocier",
     "Aucune partie n'est tenue de réparer les dommages indirects tels que la perte de profits, de clientèle, de chance ou d'exploitation, sauf faute lourde ou dolosive.",
     "Définir ce qui est « indirect » : la frontière avec le préjudice direct est la principale source de litiges."),
    ("Obligation de moyens ou de résultat", "responsabilite", "a_negocier",
     "Le Prestataire est tenu d'une obligation de [moyens / résultat] pour [décrire la prestation]. [Pour les autres prestations, il met en œuvre les diligences normales d'un professionnel du secteur.]",
     "Qualifier l'obligation évite que le juge le fasse à votre place : le prestataire a intérêt à stipuler une obligation de moyens."),
    ("Garantie de conformité et de vices cachés", "responsabilite", "standard",
     "Le Vendeur garantit que les biens sont conformes à la description convenue, propres à l'usage auquel ils sont destinés et exempts de vice caché. La garantie dure [12] mois à compter de la réception ; pendant ce délai, le Vendeur répare ou remplace les biens défectueux, ou, à défaut, rembourse leur prix.",
     "Prévoir la procédure de réclamation (délai, preuve) et l'articuler avec la clause de réception."),
    ("Garantie de passif (cession de titres)", "responsabilite", "sensible",
     "Le Cédant garantit le Cessionnaire contre toute diminution d'actif ou augmentation de passif de la Société résultant de faits ou obligations dont l'origine est antérieure au [date de cession], dans la limite d'un plafond de [montant] et d'une franchise de [montant], pendant [36] mois à compter de la cession.",
     "À rapprocher des déclarations et garanties de la convention : fixer plafond, franchise, durée et procédure de réclamation."),
    ("Garantie de non-contrefaçon", "propriete_intellectuelle", "sensible",
     "Le Prestataire garantit que les Livrables ne portent atteinte à aucun droit de propriété intellectuelle de tiers et prend en charge les frais, condamnations et indemnités résultant d'une action en contrefaçon, sous réserve que le Client l'informe sans délai de toute réclamation et lui laisse la conduite de la défense.",
     "Prévoir la conduite de la défense et la faculté de remplacer ou modifier l'élément litigieux."),

    # --- Exclusivité, non-sollicitation
    ("Exclusivité territoriale", "exclusivite", "a_negocier",
     "Le Fournisseur concède au Distributeur l'exclusivité de la distribution des Produits sur le territoire de [territoire] pendant la durée du Contrat. En contrepartie, le Distributeur s'interdit de distribuer des produits concurrents sur ce territoire.",
     "Définir précisément le territoire, les produits et les ventes passives ; l'exclusivité sera souvent liée à des objectifs minimaux."),
    ("Objectifs minimaux de vente ou d'achat", "exclusivite", "a_negocier",
     "Le Distributeur s'engage à acheter au moins [quantité / montant] de Produits par [année]. À défaut, le Fournisseur peut, après mise en demeure restée sans effet pendant [30] jours, transformer l'exclusivité en non-exclusivité ou résilier le Contrat.",
     "L'objectif doit être réaliste et lié à une sanction graduée plutôt qu'à la seule résiliation."),
    ("Non-sollicitation du personnel et des clients", "exclusivite", "a_negocier",
     "Pendant la durée du Contrat et pendant [12] mois après son terme, chaque partie s'interdit de solliciter, directement ou indirectement, le personnel de l'autre partie intervenu dans l'exécution du Contrat, ainsi que ses clients présentés dans ce cadre, sauf accord écrit.",
     "Moins contraignante qu'une non-concurrence ; durée et périmètre doivent rester proportionnés."),

    # --- Réserve de propriété, livraison, réception
    ("Réserve de propriété", "propriete", "sensible",
     "Le transfert de propriété des biens au Client est suspendu jusqu'au paiement intégral du prix en principal et accessoires. Jusqu'à cette date, le Client doit conserver les biens identifiables, les assurer et ne pas les revendre ni les donner en garantie sans l'accord du Vendeur. En cas de défaut de paiement, le Vendeur peut reprendre les biens après mise en demeure.",
     "Pour être opposable aux tiers (créanciers, procédure collective), la clause doit être écrite et acceptée au plus tard à la livraison ; vérifier les formalités de publicité en droit haïtien."),
    ("Transfert des risques et livraison", "propriete", "standard",
     "Les risques sont transférés au Client à la livraison à [lieu], conformément à l'Incoterm [FCA / DAP / autre] dans sa version en vigueur. Le Client contrôle les biens à réception et signale par écrit toute non-conformité apparente dans les [3] jours.",
     "Pour l'import-export vers Haïti, préciser qui assume transport, assurance, droits de douane et formalités."),
    ("Réception des livrables", "propriete", "standard",
     "Chaque Livrable fait l'objet d'une recette dans les [10] jours de sa livraison. Le Client notifie par écrit son acceptation ou ses réserves motivées ; à défaut de réponse dans ce délai, le Livrable est réputé accepté. Le Prestataire corrige les anomalies signalées dans un délai de [10] jours.",
     "La réception déclenche paiement et garanties : définir des critères d'acceptation objectifs."),

    # --- Propriété intellectuelle
    ("Titularité des livrables et cession de droits", "propriete_intellectuelle", "sensible",
     "Sous réserve du paiement intégral du prix, le Prestataire cède au Client, à titre exclusif, les droits patrimoniaux sur les Livrables créés spécialement pour lui, pour le monde entier et pour la durée de protection légale, pour toute exploitation. Le Prestataire conserve ses outils, méthodes et savoir-faire préexistants, qu'il concède au Client une licence non exclusive d'utilisation dans la mesure nécessaire à l'exploitation des Livrables.",
     "Une cession doit énumérer les droits cédés, le territoire et la durée ; sans écrit précis, le créateur reste titulaire. Distinguer créations nouvelles et éléments préexistants."),
    ("Licence d'utilisation non exclusive", "propriete_intellectuelle", "a_negocier",
     "Le Concédant accorde au Licencié une licence non exclusive, non transférable et non sous-licenciable d'utiliser [l'œuvre / le logiciel / la marque] sur le territoire de [territoire] pendant [durée], pour les seuls besoins de [finalité]. Toute autre utilisation est interdite.",
     "Préciser les usages permis, le nombre d'utilisateurs ou de sites, et le sort des mises à jour."),

    # --- Cession et sous-traitance
    ("Cession du contrat", "cession", "standard",
     "Aucune partie ne peut céder ou transférer tout ou partie de ses droits et obligations au titre du Contrat sans l'accord écrit préalable de l'autre partie, qui ne peut le refuser de manière abusive. Une cession entre sociétés d'un même groupe est permise sur notification préalable.",
     "Prévoir si le cédant reste solidairement tenu après la cession."),
    ("Sous-traitance sous conditions", "cession", "a_negocier",
     "Le Prestataire peut confier une partie de ses obligations à un sous-traitant avec l'accord écrit préalable du Client. Il demeure seul responsable de l'exécution du Contrat envers le Client et impose à ses sous-traitants des obligations de confidentialité et de conformité au moins équivalentes.",
     "Demander la liste des sous-traitants et un droit d'objection : c'est un point de contrôle important pour le donneur d'ordre."),
    ("Changement de contrôle", "cession", "sensible",
     "Chaque partie informe l'autre sans délai de tout changement de contrôle [au sens de [définition]] la concernant. En cas de changement de contrôle au profit d'un concurrent de l'autre partie, celle-ci peut résilier le Contrat par notification écrite dans les [60] jours de l'information, sans indemnité.",
     "Définir le contrôle (seuil de détention, pouvoir de nommer les dirigeants) ; très utile dans les contrats longs ou exclusifs."),

    # --- Données
    ("Protection des données personnelles", "donnees", "sensible",
     "Chaque partie traite les données personnelles reçues de l'autre uniquement pour les finalités du Contrat, dans le respect du droit applicable. Le Prestataire n'agit que sur instruction documentée du Client, limite l'accès aux personnes habilitées, ne transfère pas les données hors de [pays / zone] sans accord préalable et les restitue ou les détruit à la fin du Contrat.",
     "Le droit haïtien est peu développé sur ce point : appliquer néanmoins les standards de sécurité et de finalité, et vérifier le droit de l'État de résidence des personnes concernées (Québec, UE, États-Unis)."),
    ("Sécurité et incident de données", "donnees", "sensible",
     "Chaque partie met en œuvre des mesures techniques et organisationnelles raisonnables pour protéger les données contre l'accès non autorisé, la perte ou l'altération. Elle notifie à l'autre, dans les [48] heures de sa découverte, tout incident affectant ces données, avec les informations nécessaires pour en limiter les conséquences.",
     "Le délai de notification doit être réaliste mais court ; annexer au besoin une description des mesures de sécurité."),

    # --- Imprévision, force majeure
    ("Renégociation en cas de changement de circonstances (imprévision)", "imprevision", "sensible",
     "Si un changement imprévisible de circonstances rend l'exécution du Contrat excessivement onéreuse pour une partie, celle-ci peut demander la renégociation du Contrat par notification écrite motivée. Les parties négocient de bonne foi pendant [30] jours en continuant d'exécuter le Contrat. À défaut d'accord, elles peuvent saisir [le médiateur / l'arbitre] pour adapter le Contrat ou y mettre fin à la date et aux conditions qu'il fixe.",
     "Le droit civil d'inspiration napoléonienne ne reconnaît pas, en principe, la révision judiciaire pour imprévision : seule une clause contractuelle l'organise (à vérifier en droit haïtien). Précis sur les seuils (variation de coût, de change) pour éviter les abus."),
    ("Force majeure — suspension puis résiliation", "force_majeure", "standard",
     "La partie empêchée notifie l'événement de force majeure dans les [5] jours, en précisant sa durée prévisible et les mesures prises. Ses obligations sont suspendues pendant la durée de l'empêchement. Si celui-ci dépasse [60] jours, chaque partie peut résilier le Contrat par notification écrite, sans indemnité. Sont notamment considérés comme force majeure : catastrophe naturelle, guerre, émeute ou blocage généralisé des routes, décision d'une autorité rendant l'exécution impossible.",
     "Lister les événements et distinguer ceux qui excluent les obligations de paiement ; en contexte haïtien, traiter explicitement l'insécurité, les blocages de routes et ports et les pénuries de carburant."),

    # --- Résiliation
    ("Résiliation de plein droit (clause résolutoire)", "resiliation", "sensible",
     "En cas de manquement d'une partie à l'une de ses obligations essentielles resté sans effet [30] jours après mise en demeure par lettre recommandée ou courriel avec accusé de réception visant la présente clause, l'autre partie peut résilier le Contrat de plein droit, sans autre formalité ni décision de justice, sans préjudice de dommages-intérêts.",
     "La mise en demeure doit viser la clause pour qu'elle joue ; lister les obligations « essentielles »."),
    ("Résiliation pour convenance avec préavis", "resiliation", "a_negocier",
     "Chaque partie peut mettre fin au Contrat sans motif moyennant un préavis écrit de [90] jours. [La partie qui résilie verse à l'autre une indemnité égale à [montant ou formule].]",
     "Évite une durée trop rigide ; l'indemnité de sortie compense les investissements réalisés."),
    ("Résiliation en cas d'insolvabilité", "resiliation", "sensible",
     "Chaque partie peut résilier le Contrat par notification écrite si l'autre cesse ses paiements, est dissoute, fait l'objet d'une procédure collective ou ne peut plus faire face à son passif exigible.",
     "Vérifier l'effet des procédures collectives en droit haïtien : certaines règles d'ordre public limitent la résiliation au seul motif de la faillite."),
    ("Conséquences de la fin du contrat", "resiliation", "standard",
     "À la fin du Contrat, pour quelque cause que ce soit : (a) les sommes dues deviennent exigibles pour les prestations réalisées ; (b) chaque partie restitue ou détruit les documents et informations confidentielles de l'autre ; (c) les clauses qui, par nature, doivent survivre (confidentialité, responsabilité, propriété intellectuelle, règlement des différends) continuent à produire effet.",
     "Énumérer les clauses qui survivent : la fin du contrat n'efface pas tout."),

    # --- Confidentialité
    ("Exceptions à la confidentialité et divulgation légale", "confidentialite", "standard",
     "L'obligation de confidentialité ne s'applique pas aux informations qui (a) sont ou deviennent publiques sans faute du destinataire, (b) étaient déjà connues de lui, (c) lui sont communiquées légitimement par un tiers, ou (d) doivent être divulguées en vertu d'une loi ou d'une décision d'une autorité, sous réserve d'en informer l'autre partie dans la mesure permise.",
     "À associer à la clause de confidentialité de base : sans exceptions, la clause est irréaliste et plus facilement contestée."),

    # --- Conformité
    ("Anti-corruption", "conformite", "sensible",
     "Chaque partie déclare ne pas offrir, promettre ni accepter, directement ou indirectement, d'avantage indu à un agent public ou privé pour obtenir ou conserver un avantage dans le cadre du Contrat, et respecter les lois anti-corruption applicables. Toute violation constitue un manquement grave justifiant la résiliation immédiate.",
     "Particulièrement important si une partie est soumise à une loi extraterritoriale (États-Unis, Canada, Royaume-Uni, France) ; prévoir un droit de vérification."),
    ("Origine des fonds et vérification d'identité (KYC)", "conformite", "sensible",
     "Chaque partie fournit, sur demande, les informations et pièces permettant de vérifier son identité, ses bénéficiaires effectifs et l'origine licite des fonds. Le Contrat peut être suspendu ou résilié sans indemnité si ces vérifications ne peuvent être menées ou révèlent une irrégularité.",
     "Utile pour les paiements transfrontaliers et avec la diaspora ; documenter les vérifications effectuées."),

    # --- Fiscalité
    ("Répartition des taxes, droits et frais", "fiscalite", "standard",
     "Chaque partie supporte les impôts qui la frappent personnellement. Les taxes sur le chiffre d'affaires sont [en sus du prix / incluses]. Les droits d'enregistrement et de timbre, et les frais du Contrat, sont supportés par [la partie / par moitié].",
     "Vérifier avec un fiscaliste le régime de TCA, de retenue et d'enregistrement applicable aux flux concernés."),
    ("Majoration de la retenue à la source (gross-up)", "fiscalite", "sensible",
     "Si une retenue ou déduction fiscale est exigée sur un paiement, la partie payeuse majore la somme versée afin que l'autre reçoive, nette de cette retenue, le montant qu'elle aurait reçu en l'absence de retenue, et lui remet le justificatif officiel de paiement.",
     "Clause coûteuse pour le payeur ; à négocier avec un plafond ou en tenant compte d'une convention fiscale éventuelle."),

    # --- Pénale
    ("Indemnité forfaitaire de retard de livraison", "penale", "a_negocier",
     "En cas de retard de livraison imputable au Prestataire, celui-ci doit au Client une indemnité de [0,5] % du prix par jour ouvrable de retard, plafonnée à [10] % du prix. Cette indemnité est exclusive de tous autres dommages-intérêts pour retard, sans préjudice du droit de résilier.",
     "Le plafond et le caractère exclusif protègent le prestataire ; vérifier si le juge peut modérer une indemnité manifestement excessive."),
    ("Arrhes et dédit", "penale", "a_negocier",
     "Les sommes versées à la signature à titre d'arrhes ne valent pas acompte. Chaque partie peut renoncer au Contrat avant [date] : le Client en perdant les arrhes, le Vendeur en les restituant au double.",
     "Qualifier clairement arrhes ou acompte : l'effet est très différent sur la faculté de dédit."),

    # --- Droit applicable, juridiction
    ("Droit applicable et langue du contrat", "droit_applicable", "standard",
     "Le Contrat est régi par le droit haïtien. Il est rédigé en [français] ; en cas de traduction, la version française fait foi.",
     "Pour un contrat international, le choix du droit est possible sous réserve des règles d'ordre public ; vérifier son effet sur l'exécution à l'étranger."),
    ("Compétence exclusive des tribunaux", "droit_applicable", "standard",
     "À défaut d'accord amiable dans les [30] jours, tout litige relatif au Contrat relève de la compétence exclusive des tribunaux de [Port-au-Prince], sous réserve des mesures urgentes ou conservatoires pouvant être demandées à toute juridiction compétente.",
     "Prévoir le tribunal par sa ville et sa nature (civil, commerce) ; pour un exécutant à l'étranger, vérifier la reconnaissance des jugements."),
    ("Arbitrage", "droit_applicable", "sensible",
     "Tout différend découlant du Contrat ou en relation avec lui est tranché définitivement selon le règlement d'arbitrage de [institution d'arbitrage] par [un / trois] arbitre(s) nommé(s) conformément à ce règlement. Le siège de l'arbitrage est [ville]. La langue de l'arbitrage est le [français]. La sentence est définitive et lie les parties.",
     "L'arbitrage est confidentiel et souvent plus rapide, mais coûteux ; vérifier l'exécution de la sentence en Haïti et à l'étranger avant de choisir siège et institution."),
    ("Escalade : négociation, médiation, juridiction", "reglement_differends", "a_negocier",
     "Les parties tentent d'abord de résoudre tout différend par négociation entre leurs représentants dans les [15] jours de la notification du différend, puis par médiation conduite par [médiateur / institution] dans les [45] jours suivants. À défaut d'accord, chaque partie peut saisir la juridiction compétente ou, s'il en existe une, l'instance d'arbitrage désignée.",
     "Préciser que ces étapes n'empêchent pas les mesures urgentes ni ne suspendent les délais de prescription."),

    # --- Assurance, audit, information
    ("Assurance responsabilité civile", "assurance_audit", "standard",
     "Le Prestataire souscrit et maintient pendant toute la durée du Contrat une assurance couvrant sa responsabilité civile professionnelle pour un montant d'au moins [montant] par sinistre, et en remet l'attestation au Client sur demande.",
     "Si l'assurance est difficilement accessible localement, convenir d'une garantie équivalente (garantie bancaire, cautionnement)."),
    ("Droit d'audit et de contrôle", "assurance_audit", "a_negocier",
     "Le Client peut, moyennant un préavis de [10] jours ouvrables et pas plus d'une fois par an (sauf soupçon sérieux de manquement), faire vérifier par lui-même ou un auditeur tenu au secret la conformité de l'exécution du Contrat. Le Prestataire collabore et fournit les documents raisonnablement nécessaires.",
     "Encadrer fréquence, préavis, périmètre et confidentialité des informations de tiers."),
    ("Obligation d'information et d'alerte", "assurance_audit", "standard",
     "Chaque partie informe l'autre sans délai de tout événement susceptible d'affecter significativement l'exécution du Contrat, notamment tout litige, toute modification de sa situation juridique ou financière et toute difficulté d'approvisionnement ou d'exécution.",
     "Complète la clause de bonne foi ; son non-respect peut aggraver la responsabilité de la partie silencieuse."),

    # --- Clauses finales
    ("Intégralité de l'accord", "clauses_finales", "standard",
     "Le Contrat et ses annexes expriment l'intégralité de l'accord des parties sur son objet et remplacent tout accord, engagement ou communication antérieurs, écrits ou oraux, portant sur le même objet.",
     "Vérifier que tous les documents utiles (devis, cahier des charges) sont bien annexés avant de signer."),
    ("Hiérarchie des documents", "clauses_finales", "standard",
     "En cas de contradiction entre les documents contractuels, prévalent, dans l'ordre : (1) le corps du Contrat, (2) les annexes dans l'ordre de leur numérotation, (3) les conditions générales de la partie qui les a émises.",
     "Évite les « batailles de conditions générales » ; choisir l'ordre en fonction de ses intérêts."),
    ("Divisibilité", "clauses_finales", "standard",
     "Si une stipulation du Contrat est déclarée nulle ou inapplicable, les autres demeurent en vigueur et les parties s'efforcent de la remplacer par une stipulation valable d'effet économique équivalent.",
     "Clause de précaution classique, à compléter par une liste des clauses déterminantes si nécessaire."),
    ("Non-renonciation", "clauses_finales", "standard",
     "Le fait pour une partie de ne pas exercer un droit ou de tolérer un manquement ne vaut pas renonciation à s'en prévaloir ultérieurement. Toute renonciation doit être expresse et écrite.",
     "Protège contre l'argument selon lequel la tolérance passée vaut modification du contrat."),
    ("Modification par écrit", "clauses_finales", "standard",
     "Toute modification du Contrat fait l'objet d'un avenant écrit signé par les représentants habilités des deux parties. Aucun échange de courriels ou pratique ne peut modifier le Contrat, sauf si l'avenant le prévoit.",
     "Prévoir qui est habilité à signer ; vérifier que les avenants signés électroniquement sont possibles."),
    ("Notifications", "clauses_finales", "standard",
     "Toute notification est faite par écrit, par lettre recommandée avec accusé de réception, remise en main propre contre décharge, ou courriel avec accusé de réception, aux adresses indiquées en tête du Contrat. Elle est réputée reçue à la date de remise ou, par courriel, le jour ouvrable suivant l'envoi.",
     "Tenir à jour les adresses ; un changement d'adresse doit être notifié."),
    ("Élection de domicile", "clauses_finales", "standard",
     "Pour l'exécution du Contrat, les parties font élection de domicile à leurs adresses respectives indiquées en tête du Contrat. Tout changement est notifié à l'autre partie.",
     "Utile pour les significations et la compétence ; indispensable si une partie réside à l'étranger."),
    ("Signature électronique et exemplaires", "clauses_finales", "standard",
     "Le Contrat peut être signé en plusieurs exemplaires et par voie électronique. Les parties reconnaissent que les signatures électroniques ont, entre elles, la même valeur que des signatures manuscrites, dans la mesure permise par la loi applicable, et que les journaux d'audit du prestataire de signature font preuve de l'identité des signataires et de la date de signature.",
     "En droit haïtien, la valeur de la signature électronique est encore incertaine : pour un enjeu important, prévoir un acte authentique ou une signature certifiée (voir notre page sur la valeur juridique)."),
    ("Frais et enregistrement du contrat", "clauses_finales", "standard",
     "Chaque partie supporte ses propres frais de négociation et de conseil. Les frais d'enregistrement du Contrat, lorsqu'ils sont requis, sont supportés par [la partie / par moitié]. Les parties s'engagent à accomplir les formalités nécessaires dans les délais légaux.",
     "Certains contrats (bail, cession immobilière, constitution de sûreté) exigent un enregistrement ou un acte notarié pour être valables ou opposables : le vérifier."),
]
